import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Anime App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex flex-col justify-between mx-auto dark:bg-gray-900 bg-gray-200 no-scrollbar">
        <Header />
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
